spring:
  application:
    name: trey-client
  cloud:
    sentinel:
      transport:
        port: 9902
        dashboard: localhost:9901
    nacos:
      discovery:
        server-addr: localhost:8848
server:
  port: 8802
management:
  endpoints:
    web:
      exposure:
        include: "*"
feign:
  sentinel:
    enabled: true