spring:
  cloud:
    gateway:
#      discovery:
#        locator:
#          enabled: true
      routes:
        - id: trey-client
          uri: lb://trey-client
          predicates:
            - Path=/hello/**
#            - After=2020-07-15T14:04:54.563+08:00[Asia/Shanghai]
#            - Cookie=username,turui
#            - Header=X-Request-Id, \d+