spring:
  application:
    name: trey-server
server:
  port: 8803
eureka:
  instance:
    hostname: turui-server
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8801/eureka/