spring:
  application:
    name: register-center
server:
  port: 8801
eureka:
  instance:
    hostname: turui-pc
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8801/eureka/