server:
  port: 8805
spring:
  application:
    name: trey-consul
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
#        health-check-path: /health
management:
  endpoint:
    health:
      enabled: true